# Generated by Django 6.0.2 on 2026-03-03 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('innovation', '0009_alter_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Komanda Adı')),
                ('description', models.TextField(verbose_name='Məqsəd və Fəaliyyət')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_looking_for_members', models.BooleanField(default=True, verbose_name='Üzv axtarılır')),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_teams', to='innovation.idea')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='teams_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Müraciət mesajı')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('accepted', 'Qəbul edildi'), ('rejected', 'Rədd edildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
