# Generated by Django 6.0.2 on 2026-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='looking_for',
            field=models.CharField(blank=True, help_text='Məs: Backend, Designer, Marketer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
