# Generated by Django 6.0.2 on 2026-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammessage_file_teammessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
