# Generated by Django 6.0.2 on 2026-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_teammessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Komanda Loqosu'),
        ),
    ]
