# Generated by Django 6.0.2 on 2026-03-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0007_alter_category_id_alter_comment_id_alter_idea_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
