# Generated by Django 6.0.2 on 2026-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
