"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)mzvf6!uhhfll#xb$1$*e-5-q-j$sh=&5h6^w)$8pu8eh0ee17'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'innovation',
    'solutions',
    'teams',
    'challenges',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Bura diqqət!
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'masssolve_db',      # pgAdmin-də yaratdığın bazanın adı
        'USER': 'postgres',          # PostgreSQL quraşdıranda gələn standart istifadəçi adı
        'PASSWORD': '1234',   # PostgreSQL yükləyəndə təyin etdiyin şifrə (məsələn 1234)
        'HOST': '127.0.0.1',         # Bazanın sənin kompüterində olduğunu bildirir
        'PORT': '5432',              # Standart port, dəyişməmisənsə belə qalır
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


import os
from pathlib import Path

# BASE_DIR onsuz da yuxarıda var, onu dəyişmə
BASE_DIR = Path(__file__).resolve().parent.parent

# Statik faylların tənzimlənməsi
STATIC_URL = 'static/'

# BU HİSSƏNİ DÜZƏLT:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]



# settings.py faylının ən aşağısına bax
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Bütün fayllar layihə kökündəki 'media' qovluğuna gedəcək

# Bu hissəni əlavə et ki, Django hər app-in içindəki static qovluğunu axtarsın
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# settings.py
LOGIN_URL = '/users/login/'  # Bura sənin həqiqi login linkin olmalıdır

AUTH_USER_MODEL = 'users.User'


# settings.py
ALLOWED_HOSTS = ['my-portfolio-64bs.onrender.com', 'localhost', '127.0.0.1']
