# Generated by Django 6.0.2 on 2026-03-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Həllin Adı')),
                ('target_area', models.CharField(max_length=100, verbose_name='Hədəf Sahə')),
                ('description', models.TextField(verbose_name='Texniki İzah')),
                ('image', models.ImageField(upload_to='solutions_gallery/', verbose_name='Şəkil/Render')),
                ('technical_file', models.FileField(blank=True, null=True, upload_to='solutions_files/', verbose_name='Layihə Faylı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='independent_solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
