# Generated by Django 6.0.2 on 2026-03-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='solution_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(upload_to='solutions_gallery/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='target_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='technical_file',
            field=models.FileField(blank=True, null=True, upload_to='solutions_files/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='solutions.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
