# Generated by Django 6.0.2 on 2026-04-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_remove_solution_author_remove_solution_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionproject',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionproject',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='independent_solutions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='target_area',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='technical_file',
            field=models.FileField(blank=True, null=True, upload_to='solutions_files/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='solution_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='solutions.comment')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='solutions.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SolutionParticipant',
        ),
        migrations.DeleteModel(
            name='SolutionProject',
        ),
    ]
