# Generated by Django 6.0.2 on 2026-04-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_remove_solutionproject_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(default='', upload_to='solutions_gallery/'),
            preserve_default=False,
        ),
    ]
