# Generated by Django 6.0.2 on 2026-04-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Yarışın Adı')),
                ('description', models.TextField(verbose_name='Problemin Təsviri')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mükafat')),
                ('deadline', models.DateTimeField(verbose_name='Son Tarix (Deadline)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv (Həllər qəbul edilir)'), ('JUDGING', 'Qiymətləndirmə (Deadline bitib)'), ('FINISHED', 'Bitmiş (Qaliblər elan edilib)')], default='ACTIVE', max_length=20)),
                ('submission_type', models.CharField(choices=[('FILE', 'Yalnız Fayl'), ('LINK', 'Yalnız Link (GitHub, Figma və s.)'), ('BOTH', 'Həm Fayl, Həm Link')], default='BOTH', max_length=10)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Admin Təsdiqi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_submission', models.FileField(blank=True, null=True, upload_to='submissions/files/', verbose_name='Həll Faylı')),
                ('link_submission', models.URLField(blank=True, max_length=500, null=True, verbose_name='Həll Linki')),
                ('description', models.TextField(blank=True, verbose_name='Həll haqqında qısa izah')),
                ('score', models.IntegerField(default=0, verbose_name='Münsif Xalı')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Münsif Rəyi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
    ]
