# Generated by Django 6.0.2 on 2026-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
